name: Update XKCD Comic

on:
  schedule:
    - cron: "0 0 * * *"  # Runs the script every day at midnight (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display current date and time
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S') - Starting workflow"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S') - Installing requirements"
          pip install -r requirements.txt

      - name: Run script
        id: run_script
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S') - Executing python script"
          python main.py

      - name: Extract comic number
        id: extract_comic_number
        run: |
          comic_number=$(jq -r '.num' ${{ steps.run_script.outputs.stdout }})
          echo "COMIC_NUMBER=$comic_number" >> $GITHUB_ENV

      - name: Commit and push changes
        run: |
          echo "$(date +'%Y-%m-%d %H:%M:%S') - Committing and pushing changes"
          git config --global user.email "ShashashankThakur@users.noreply.github.com"
          git config --global user.name "Shashank Thakur"
          git add README.md
          git commit -m "automated update - XKCD #${{ env.COMIC_NUMBER }}"
          git push
